frontend code for disabling direction display on embedded map
LycheeOrg/Lychee-front pull request #243
Opened 2021-01-27 10:42 UTC by sjml

This is the frontend code addressing LycheeOrg/Lychee#886, reading the configuration object and not displaying the directional cone if the setting is off.

2021-01-27 11:22 UTC, ildyria requested changes
This is fine but you are missing changes in 
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/lychee.js

Currently `lychee.map_display_direction` is not set.

2021-01-27 11:34 UTC, sjml commented
> This is fine but you are missing changes in
> https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/lychee.js
> 
> Currently `lychee.map_display_direction` is not set.

Ah, thanks. I had thought that object was auto-populated from the database.

2021-01-27 12:02 UTC, ildyria commented
You may want to add something in line 200 and line 270 something in the `script/lychee.js`

2021-01-27 12:04 UTC, sjml commented
> You may want to add something near line 200 and line 270 in the `script/lychee.js`

Will do. I'll set it to default to `true`.

2021-01-28 10:33 UTC, sjml commented
This should all be set correctly now. @ildyria, look good to you?

2021-01-28 10:34 UTC, ildyria approved these changes
LGTM.

2021-01-28 12:56 UTC, sjml commented
Looking some more -- what about hiding the "Direction" data in the sidebar? I can do a push that accomplishes that, too, but could see it being a conceptually different thing (raw EXIF data vs. map visualization).

2021-01-28 13:07 UTC, ildyria commented
> Looking some more -- what about hiding the "Direction" data in the sidebar? I can do a push that accomplishes that, too, but could see it being a conceptually different thing (raw EXIF data vs. map visualization).

I don't have a strong opinion on that to be honest. My camera needs to be connected to my phone if I want to have GPS coordinates. Map visualization is very nice, but the use in practice makes it useless for me. I do see its use with phones but as a photographer, why would I take pictures with my phone when I can have better results with my full-frame camera. 

Then again in the case of phones, we need to trust the integrated compass which from experience is often off...

Conclusion, I don't care, maybe the other will have a stronger opinion.

By the way, feel free to drop on our gitter: https://gitter.im/LycheeOrg/Lobby you can easily login with your github ID. :)

2021-01-30 11:01 UTC, merged